/* keyboard.h - Defines used in interactions with the keyboard */

#include "types.h"

#define KB_DATA_PORT      0x60
#define KB_CMD_PORT       0x64
#define KB_IRQ            1

#define MODS              4
#define KEYS              60
#define BUFFER_SIZE       128
#define RELEASED          0
#define PRESSED           1 
#define CAPS_PRESSED      2

#define L_SHIFT_PRESS     0x2A
#define L_SHIFT_RELEASE   0xAA
#define R_SHIFT_PRESS     0x36
#define R_SHIFT_RELEASE   0xB6
#define CTRL_PRESS        0x1D
#define CTRL_RELEASE      0x9D
#define CAPS_LOCK         0x3A
#define ENTER             0x1C
#define ALT_PRESS         0x38
#define ALT_RELEASE       0xB8  

#define SCANCODE_L        0x26
#define SCANCODE_C        0x2E
#define BACKSPACE         0x0E
#define TAB               0x0F

#define F1_PRESS          0x3B
#define F2_PRESS          0x3C
#define F3_PRESS          0x3D                

//https://wiki.osdev.org/PS/2_Keyboard
//source for most of these scan codes




/* Initializes keyboard to use scan code 1 and enables the
 * associated IRQ on the PIC 
 *      INPUTS: none
 *      OUTPUTS: none
 *      RETURN VALUE: none
 *      SIDE EFFECTS: enables interrupts from the keyboard
 */
void keyboard_init();

/*  For checkpoint 1, only handles single key presses and alphanumeric keys
    with some symbols.   */
/* Handles interrupts generated by the keyboard
 *  INPUTS: none
 *  OUTPUTS: none
 *  RETURN VALUE: none
 *  SIDE EFFECTS: Prints the character typed onto the screen
 */
void keyboard_handler();


uint8_t special_chars(uint8_t scan_code);


